### ISSUE TITLE
Smallrye Graphql 1.4.4-Snapshot

### ISSUE THREAD

**Issue by R4V3NN0** [eformat/graphql-federation#1]
I just tried to start your project because I have seen it in the original smallrye ticket and I was impressed because someone got it to run, but I have run into the error that maven cant find the version from smallrye-graphql .

Im expecting that Im doing something wrong but can you tell me where you get the correct version? I have pasted my error message below.

``` Could not resolve dependencies for project org.acme:production-service:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: io.smallrye:smallrye-graphql:jar:1.4.4-SNAPSHOT, io.smallrye:smallrye-graphql-cdi:jar:1.4.4-SNAPSHOT, io.smallrye:smallrye-graphql-schema-builder:jar:1.4.4-SNAPSHOT: Could not find artifact io.smallrye:smallrye-graphql:jar:1.4.4-SNAPSHOT ```

**Comment by eformat** [comment]
the build of `1.4.4-SNAPSHOT` is documented here https://github.com/eformat/graphql-federation#graphql-microservices
build and install this:

https://github.com/t1/smallrye-graphql/tree/521-federation-into-core

this branch exposes sdl api, so apollo can query the services OK. 
however the services are not yet printing the Federation annotations in the sdl e.g. @key @extends etc
so am stuck there at the moment.
